const translator = {
  home: {
    frontEnd: {
        BazarShow:['بازار شۆ','بازار شو','BazarShow','Bazar gösterisi','بازارشو'],
        Cart:['سەبەتە','سله','Cart','arabası','سبد','Charrette','Karren'],
        UserProfile:['زانیاری بەکارهێنەر','تعريف المستخدم','User Profile','Kullanıcı Profili','مشخصات کاربر','Profil de l’utilisateur','Benutzerprofil'],
        OrderHistory:['لیستی داواکاری','سجل الطلبات','Order History','Sipariş Geçmişi','تاریخچه نظم','Historique des commandes','Bestellhistorie'],
        SignOut:['چوونە دەرەوە','تسجيل الخروج','Sign Out','Oturumu Kapat','خارج شدن','Se déconnecter','Abmelden'],
        SignIn:['چوونەژوورەوە','تسجيل الدخول','Sign In','Oturum Aç','ورود به برنامه','Connexion','Anmelden'],
        Admin:['بەڕێوەبەر','مدیر','Admin','yönetici','مدیر','Admin','Administrator'],
        Dashboard:['کورتە','لوحه القياده','Dashboard','Tablo','داشبورد','Tableau de bord','Instrumententafel'],
        Products:['بەرهەمەکان','منتجات','Products','Ürünler','محصولات','Produits','Produkte'],
        Orders:['داواکارییەکان','طلبات','Orders','Sipariş','سفارشات','Ordres','Aufträge'],
        Users:['بەکارهێنەران','المستخدمين','Users','Kullanıcı','کاربران','Utilisateurs','Benutzer'],
        Categories:['جۆری کاڵا','الفئات','Categories','Kategori','دسته','Catégories','Kategorien'],
        Allrightsreserved:['هەموو مافەکان پارێزراون','جميع الحقوق محفوظة','All rights reserved','Tüm hakları saklıdır','تمام حقوق این سایت متعلق به وب سایت ترفندستان می باشد.','Tous droits réservés','Alle Rechte vorbehalten'],
        FeaturedProducts:['بەرهەمە تایبەتەکان','المنتجات المميزة','Featured Products','Öne Çıkan Ürünler','محصولات برجسته','Produits en vedette','Vorgestellte Produkte'],
        NoProductAvailable:['هیچ بەرهەمێک بەردەست نیە','لا يوجد منتج متوفر','No Product Available','Ürün Yok','هیچ محصولی در دسترس نیست','Aucun produit disponible','Kein Produkt verfügbar',]
        
    },
    backEnd: {},
    error: {},
  },
  product:{
    frontEnd:{
      Outofstock:['بەردەست نیە','غير متوفر في المخزن','Out of stock','Stokta yok','خارج از سهام','Rupture de stock','Nicht auf Lager',],
    SorryProductisoutofstock:['ببووره. بەرهەم لە کەمترە لە داواکارییەکەت','معذرة. المنتج غير متوفر','Sorry. Product is out of stock','Pardon. Ürün stokta yok','متاسفم. محصول خارج از سهام است','Pardon. Le produit est en rupture de stock','Tut mir Leid. Produkt ist nicht vorrätig',],
    
    Pleaseentercommentandrating:['تکایە لێدوان و هەڵسەنگاندن تێبنووسە','الرجاء إدخال التعليق والتقييم','Please enter comment and rating','Lütfen yorum ve derecelendirme girin','لطفا نظر و رتبه بندی را وارد کنید','Veuillez saisir le commentaire et l’évaluation','Bitte Kommentar und Bewertung eingeben',],
    Price:['نرخ','ثمن','Price','fiyat','قيمت','prix','Preis',],
    Description:['ناساندن','الوصف','Description','Açıklama','توصیف','Description','Beschreibung',],
    Status:['دۆخ','حالة','Status','Durum','وضعیت','Statut','Status',],
    InStock:['بەردەستە','متوفر في المخزن','In Stock','en stock','در سهام','En stock','vorrätig',],
    Unavailable:['بەردەست نیە','غير متوفر','Unavailable','Kullanılamaz','دسترس نیست','Indisponible','Nicht verfügbar',],
    AddtoCart:['زیادکردن بۆ کارت','اضف الى سلة التسوق','Add to Cart','Sepete Ekle','افزودن به سبد خرید','Ajouter au panier','In den Warenkorb',],
    Reviews:['پێداچوونەوەکان','ملاحظات','Reviews','Değerlendirme -leri','بررسی','Critiques','Rezensionen',],
    Thereisnoreview:['هیچ پێداچوونەوەیەک نییە','لا يوجد تقييم','There is no review','Yorum yok','هیچ بررسی وجود ندارد','Il n’y a pas d’avis','Es gibt keine Bewertung',],
    Writeacustomerreview:['پێداچوونەوەیەکی کڕیار بنوسە','اكتب مراجعة العملاء','Write a customer review','Bir müşteri yorumu yazın','نوشتن یک بررسی مشتری','Écrire un avis client','Schreiben Sie eine Kundenbewertung',],
    Rating:['پۆلێنکردن','تقييم','Rating','Derecelendirme','امتیاز','Notation','Bewertung'],
    Select:['دیاریبکە','اختار','Select','Seçmek','انتخاب','Choisir','Auswählen',],
    Poor:['لاواز','ضعيف','Poor','Fakir','فقیر','Médiocre','Schlecht'],
    Fair:['دادپەروەرانە','معرض','Fair','Fuar','نمایشگاه','Équitable','Messe',],
    Good:['باش','جيد','Good','İyi','خوب','Bon','Gut'],
    Verygood:['زۆر باشه','جيد جداً','Very good','Çok iyi','خیلی خوب','Très bien','Sehr gut',],
    Excellent:['باشترین','ممتازة','Excellent','Mükemmel','عالی','Excellente','Ausgezeichnet',],
    Please:['تکایه','الرجاء','Please','Lütfen','لطفاً','S’il vous plaît','Bitte',],
    SignIn:['چوونەژوورەوە','تسجيل الدخول','Sign In','Oturum Aç','ورود به برنامه','Connexion','Anmelden',],
    towriteareview:['بۆ نووسینی تێبینی','لكتابة مراجعة','to write a review','yorum yazmak için','برای نوشتن یک بررسی','pour écrire un avis','um eine Rezension zu schreiben',],
    Reviewsubmittedsuccessfully:['تێبینی بەسەرکەوتوویی تۆمارکرا','تم إرسال المراجعة بنجاح','Review submitted successfully','İnceleme başarıyla gönderildi','بررسی ارسال شده با موفقیت','Examen soumis avec succès','Überprüfung erfolgreich eingereicht'],
    Submit:['ناردن','إرسال','Submit','Gönder','ارسال','Envoyer','Senden'],
    Comments:['لێدوانەکان','التعليقات','Comments','Yorum','نظرات','Commentaires','Kommentare'],
    Leaveacommenthere:['لێدوانێک لێرە بەجێبێنە','اکتب تعليقا هنا','Leave a comment here','Buraya yorum bırakın','نظر را اینجا بگذارید','Laissez un commentaire ici','Hinterlasse hier einen Kommentar'],
    reviews:['پێداچوونەوە','تعلیق','reviews','Değerlendirme -leri','بررسی','critiques','rezensionen'],
  }},
  search: {
    frontEnd: {
      searchproducts:['بەدوای بەرهەمەکاندا بگەڕێ','البحث عن المنتجات','search products','ürünleri ara','جستجو محصولات','Rechercher des produits','Produkte suchen'],
      to:['بۆ','الى','to','ila','تا','à','bis'],
      starsup:['ئەستێرە و زیاتر','نجوم وما فوق','stars & up','','stars ve üzeri','ستاره و بالاتر','étoiles et plus','Sterne & mehr'],
      Department:['جۆری کاڵا','قسم','Department','','گروه','Département','Abteilung'],
      Any:['هەموی','أي','Any','Herhangi','هر','Quelconque','Jegliche',],
      Price:['نرخ','ثمن','Price','fiyat','قيمت','prix','Preis',],
      AvgCustomerReview:['تێکڕای پێداچوونەوەی کڕیار','متوسط مراجعة العملاء','Avg. Customer Review','Ortalama Müşteri İncelemesi','متوسط. بررسی مشتری','Moyenne. Avis client','Durchschnitt. Kundenrezension'],
      up:['و زیاتر',' وما فوق',' & up','ve üzeri',' و به بالا','et plus',' und höher',],
      Sortby:['ڕیزکردن بەپێی','ترتيب حسب','Sort by','Sıralama ölçütü','مرتب سازی بر اساس','Trier par','Sortieren nach',],
      NewestArrivals:['نوێترین ڕاگەیەنراو','أحدث ما تم الإعلان عنه','Newest Arrivals','En Yeni Gelenler','جدیدترین اعلام کرد','Annonce du plus récent','Neueste angekündigt',],
      PriceLowtoHigh:['نرخ: نزم بۆ بەرز','السعر: من الأقل إلى الأعلى','Price: Low to High','Fiyat: Düşükten Yükseğe','قیمت: پایین به بالا','Prix: Faible à élevé','Preis: Niedrig bis Hoch',],
      PriceHightoLow:['نرخ: بەرز بۆ نزم','السعر: من الأعلى إلى الأدنى','Price: High to Low','Fiyat: Yüksekten Düşüğe','قیمت: بالا به پایین','Prix: Haut à Bas','Preis: Hoch bis Niedrig'],
      AvgCustomerReviews:['چاوپێخشاندنەوەکانی کڕیار','متوسط آراء العملاء','Avg. Customer Reviews','Ort. Müşteri Yorumları','نظرات مشتری به طور متوسط','Commentaires moyens des clients','Durchschnittliche Kundenrezensionen',],
      NoProductFound:['هیچ بەرهەمێک نەدۆزرایەوە','لم يتم العثور على منتج','No Product Found','Ürün Bulunamadıلم يتم العثور على منتج','هیچ محصولی یافت نشد','Aucun produit trouvé','Kein Produkt gefunden',],
      Results:['ئەنجام','النتائج','Results','Sonuçlar','نتایج','Résultats','Ergebnisse',],
      
      
    },
    backEnd: {},
    error: {},
  },
  cart: {
    frontEnd: {
      SorryProductisoutofstock:['ببووره. بەرهەم بەردەست نییە','معذرة. المنتج غير متوفر','Sorry. Product is out of stock','Pardon. Ürün stokta yok','متاسفم. محصول خارج از سهام است','Pardon. Le produit est en rupture de stock','Tut mir Leid. Produkt ist nicht vorrätig'],
      ShoppingCart:['کارتی بازاڕکردن','سلة التسوق','Shopping Cart','Alışveriş Sepeti','سبد خرید','Caddie','Einkaufswagen'],
      Cartisempty:['کارت بەتاڵە','سلة التسوق فارغة.','Cart is empty.','Sepet boş.','سبد خرید خالی است.','Le panier est vide.','Warenkorb ist leer.'],
      GoShopping:['بڕۆ بۆ بازاڕکردن','تسوق','Go Shopping','Alışverişe Çık','برو خرید','Faire les magasins','Einkaufen gehen'],
      Subtotal:['کۆ','المجموع الفرعي  ','Subtotal','Ara toplam','زیرمجموعه','Sous-total','Zwischensumme'],
      items:['مادە','العناصر','items','eşya','موارد','Articles','Artikel'],
      ProceedtoCheckout:['بەردەوامبە بۆ کڕین','تابع الشراء','Proceed to Checkout','Satın almaya devam et','اقدام به پرداخت','Passer à la caisse','Weiter zur Kasse'],
      

    },
    backEnd: {},
    error: {},
  },
  Customer: {
    frontEnd: {
      SignIn:['چوونەژوورەوە','تسجيل الدخول','Sign In','Oturum Aç','ورود به برنامه','Connexion','Anmelden'],
      Email:['ئیمەیڵ','البريد الإلكتروني','Email','E-posta','پست الکترونیک','Messagerie électronique','E-Mail',],
      Password:['پاسۆرد','كلمه مرور','Password','Parola','رمز عبور','Mot de passe','Passwort',],
      Newcustomer:['کڕیاری نوێ','عميل جديد','New customer','Yeni müşteri','مشتری جدید','Nouveau client','Neukunde',],
      Createyouraccount:['ئەژمێرەکەت دروست بکە','أنشئ حسابك','Create your account','Hesabınızı oluşturun','ایجاد حساب کاربری','Créez votre compte','Erstellen Sie Ihr Konto',],
      Passwordsdonotmatch:['پاسۆردەکان ناگونجێن','كلمات المرور غير متطابقة','Passwords do not match','Şifreler eşleşmiyor','رمزهای عبور مطابقت نمی کنند','Les mots de passe ne correspondent pas','Kennwörter stimmen nicht überein',],
      SignUp:['خۆ تۆمارکردن','التسجيل','Sign Up','Kaydol','ثبت نام','S’enregistrer','Anmelden',],
      Alreadyhaveanaccount:['پێشتر ئەژمێرێت هەیە؟','لديك حساب بالفعل؟','Already have an account?','Zaten bir hesabınız var?','در حال حاضر یک حساب کاربری؟','Vous avez déjà un compte?','Sie haben bereits ein Konto?',],
      Name:['ناو','الاسم','Name','Ad','نام','Nom','Name',],
      ConfirmPassword:['پشتڕاستکردنەوەی پاسۆرد','تأكيد كلمة المرور','Confirm Password','Şifreyi Onayla','تایید رمز عبور','Confirmer le mot de passe','Passwort bestätigen',],
      UserProfile:['زانیاری بەکارهێنەر','تعريف المستخدم','User Profile','Kullanıcı Profili','مشخصات کاربر','Profil de l’utilisateur','Benutzerprofil'],
      Update:['نوێکردنەوە','تحديث','Update','Güncelleştirmek','روز رسانی','Mettre à jour','Aktualisieren',],
      userdeletedsuccessfully:['','','user deleted successfully','','','','',],  
      Users:['بەکارهێنەران','المستخدمين','Users','Kullanıcı','کاربران','Utilisateurs','Benutzer'],
      ID:['کۆد','رمز','ID','Kimliği','شناسه','Id','Id',],
      ACTIONS:['چالاکی','الاجراءات','ACTIONS','EYLEMLER','اقدامات','ACTIONS','AKTIONEN',],       
      Edit:['دەستکاری','حرر','Edit','Düzenlemek','ویرایش','Éditer','Redigieren',],
      Delete:['سڕینەوە','حذف','Delete','Silmek','حذف','Supprimer','Löschen',],
      ISADMIN:['بەڕێوەبەرە','هو المشرف','IS ADMIN','YÖNETİCİSİDİR','مدیر است','EST ADMIN','IST ADMIN',],
      ISSUPERADMIN:['گەورە بەڕێوەبەرە','هو المشرف المتميز','IS SUPER ADMIN','YÖNETİCİSİDİR','مدیر فوق العاده است','est super administrateur','ist Super-Admin',],
      
      YES:['بەڵێ','نعم','YES','Evet','بله','Oui','Ja',],
      No:['نەخێر','لا','No','Hayır','نه','Non','Nein',],  
    },
    backEnd: {},
    error: {},
  },
  Shipping:{
    frontEnd:{
      ShippingAddress:['ناونیشانی گەیاندن','عنوان الشحن','Shipping Address','Teslimat Adresi','آدرس حمل و نقل','Adresse de livraison','Lieferadresse',],
      FullName:['ناوی تەواو','الاسم الكامل','Full Name','Tam İsim','نام کامل','Nom complet','Vollständiger Name',],
      Address:['ناونیشان','عنوان','Address','Adres','آدرس','Adresse','Adresse',],
      City:['شار','مدينة','City','Şehir','شهر','Ville','Stadt',],
      PostalCode:['ژمارەی تەلەفۆن','رقم الهاتف','Phone Numer','Telefon numarası','شماره تلفن','Numéro de téléphone','Telefonnummer',],
      Country:['وڵات','بلد','Country','Ülke','کشور','Pays','Land',],
      Continue:['بەردەوامبە','استمر','Continue','Devam etmek','ادامه','Continuer','Fortsetzen'],
      Shipping:['گەیاندن','شحن','Shipping','Nakliye','نقل','Livraison','Versand',],
      Payment:['پارەدان','دفع','Payment','Ödeme','پرداخت','Paiement','Zahlung',],
      PlaceOrder:['تۆمارکردنی کڕین','تقديم الطلب','Place Order','Sipariş Ver','درخواست سفارش','Passer commande','Bestellung aufgeben',],
      PaymentMethod:['شێوازی پارەدان','طريقة الدفع','Payment Method','Ödeme Yöntemi','روش پرداخت','Mode de paiement','Zahlungsmethode',],
      PreviewOrder:['بینینی داواکاری','معاينة الطلب','Preview Order','Önizleme Siparişi','سفارش پیش نمایش','Aperçu de l’ordre','Vorschau Bestellung',],
      Edit:['دەستکاری','حرر','Edit','Düzenlemek','ویرایش','Éditer','Redigieren',],
      Items:['یەکە','العناصر','Items','Eşya','موارد','Articles','Artikel',],
      ItemsList:['مادەکان','العناصر','Items','Eşya','موارد','Articles','Artikel',],
      
      OrderSummary:['پوختەی داواکاری','ملخص الطلب','Order Summary','Sipariş Özeti','خلاصه سفارش','Récapitulatif de la commande','Zusammenfassung der Bestellung',],
      Tax:['باج','ضريبة','Tax','Vergi','مالیات','Taxe','Steuer',],
      OrderTotal:['کۆی گشتی','إجمالي الطلب','Order Total','Toplam Sipariş','مجموع سفارش','Total de la commande','Bestellsumme',],
      Order:['داواکاری','الطلب','Order','Sipariş','سفارش','Commande','Bestellung',],
      Deliveredat:['گەیەنراوە لە','يتم التوصيل في','Delivered at','Şurada teslim edilir','تحویل داده شده در','Livré à','Geliefert am',],
      NotDelivered:['نەگەیەنراوە','لم يتم التسليم','Not Delivered','Teslim Edilmedi','تحویل داده نشده','Non livré','Nicht geliefert',],
      Paidat:['پارە دراوە لە','تدفع في','Paid at','Ödenen','پرداخت شده در','Payé à','Bezahlt um',],
      NotPaid:['پارە نەدراوە','غير مدفوع','Not Paid','Ödenmedi','پرداخت نمی شود','Non payé','Nicht bezahlt',],
      DeliverOrder:['داواکارییەکە گەیەندرا','تسليم الطلب','Deliver Order','Siparişi Teslim Et','سفارش تحویل','Livrer la commande','Bestellung liefern',],
    }
  },
  admin: {
    frontEnd: {
      ID:['کۆد','رمز','ID','Kimliği','شناسه','Id','Id',],
      DATE:['بەروار','تاريخ','DATE','tarih','تاریخ','date','Datum',],
      TOTAL:['کۆی گشتی','مجموع','TOTAL','TOPLAM','مجموع','TOTAL','GESAMT',],
      PAID:['پارەدان','مدفوع','PAID','TARİH','پرداخت','PAYÉ','BEZAHLT',],
      DELIVERED:['گەیەنراوە','تسليم','DELIVERED','TESLİM','تحویل داده','LIVRÉ','ABGEGEBEN',],
      ACTIONS:['چالاکی','الاجراءات','ACTIONS','EYLEMLER','اقدامات','ACTIONS','AKTIONEN',],
      OrderHistory:['لیستی داواکاری','سجل الطلبات','Order History','Sipariş Geçmişi','تاریخچه نظم','Historique des commandes','Bestellhistorie'],
      No:['نەخێر','لا','No','Hayır','نه','Non','Nein',],  
      Details:['وردەکاریەکان','التفاصيل','Details','Şey','جزئیات','Détails','Details',],
      Orders:['داواکارییەکان','طلبات','Orders','Sipariş','سفارشات','Ordres','Aufträge'],
      USER:['بەکارهێنەر','مستخدم','USER','KULLANICI','کاربر','UTILISATEUR','BENUTZER',],
      DELETEDUSER:['بەکارهێنەری سڕدراوە','المستخدم المحذوف','DELETED USER','SİLİNEN KULLANICI','کاربر حذف شده','UTILISATEUR SUPPRIMÉ','GELÖSCHTER BENUTZER',],
      Delete:['سڕینەوە','حذف','Delete','Silmek','حذف','Supprimer','Löschen',],
      Areyousuretodelete:['ئایا دڵنیایت لە سڕینەوە؟','هل أنت متأكد من الحذف؟','Are you sure to delete','Sileceğinizden emin misiniz?','آیا مطمئن هستید که حذف می کنید؟','Êtes-vous sûr de supprimer?','Sind Sie sicher, dass Sie löschen?',],
      orderdeletedsuccessfully:['داواکردن بەسەرکەوتوویی سڕایەوە','تم حذف الطلب بنجاح','order deleted successfully','sipariş başarıyla silindi','سفارش حذف شده با موفقیت','commande supprimée avec succès','Bestellung erfolgreich gelöscht',],
            
    },
    Products:{
      ID:['کۆد','رمز','ID','Kimliği','شناسه','Id','Id',],
      Name:['ناو','الاسم','Name','Ad','نام','Nom','Name',],
      Price:['نرخ','ثمن','Price','fiyat','قيمت','prix','Preis',],
      Products:['بەرهەمەکان','منتجات','Products','Ürünler','محصولات','Produits','Produkte'],
      Update:['نوێکردنەوە','تحديث','Update','Güncelleştirmek','روز رسانی','Mettre à jour','Aktualisieren',],
      ACTIONS:['چالاکی','الاجراءات','ACTIONS','EYLEMLER','اقدامات','ACTIONS','AKTIONEN',],
      Category:['پۆل','باب','Category','Kategori','رده','Catégorie','Kategorie',],
      BRAND:['براند','وسم','BRAND','DAĞLAMAK','برند','MARQUE','MARKE',],
      userOwner:['خاوەنی بەکارهێنەر','مالك المستخدم','userOwner','kullanıcı Sahibi','صاحب کاربر','utilisateur Propriétaire','Benutzer Eigentümer',],
      CreatedDate:['بەرواری دروست کردن','تاريخ الإنشاء','Created Date','Oluşturulma Tarihi','تاریخ ایجاد شده','Date de création','Erstellungsdatum',],
      UpdateDate:['بەرواری نوێکردنەوە','تاريخ التحديث','Update Date','Güncelleme Tarihi','تاریخ به روز رسانی','Date de mise à jour','Datum der Aktualisierung',],
      CreateProduct:['بەرهەم دروست بکە','إنشاء منتج','Create Product',' Ürün Oluştur','ایجاد محصول','Créer un produit','Produkt erstellen',],
      PriceUnit:['یەکەی نرخ','وحدة الأسعار','Price Unit','Fiyat Birimi','واحد قیمت','Unité de prix','Preiseinheit',],
      ImageFile:['فایلی وێنە','ملف الصورة','Image File','Görüntü Dosyası','فایل تصویر','Fichier image','Bilddatei',],
      Slug:['سڵاگ','سبيكه','Slug','Sümüklüböcek','لیسه','Limace','Nacktschnecke',],
      UploadImage:['بارکردنی وێنە','تحميل الصورة','Upload Image','Resim Yükle',' آپلود تصویر','Télécharger l’image','Bild hochladen',],
      AdditionalImages:['وێنەی زیادە','صور إضافية','Additional Images','Ek Görseller','تصاویر اضافی','Images supplémentaires','Weitere Bilder',],
      UploadAditionalImage:['بارکردنی وێنەی زیادە',' تحميل صورة إعلانية','Upload Aditional Image','Ek Resim Yükle','آپلود تصویر اضافی','Télécharger une image supplémentaire','Zusätzliches Bild hochladen',],
      CountInStock:['ژمارەی بەردەست','لعد في المخزون','Count In Stock','Stokta Sayın','تعداد در سهام','Compter en stock','Auf Lager zählen',],
      Description:['پێناسە','الوصف','Description','Açıklama','توصیف','Description','Beschreibung',],
      EditProduct:['بژارکردنی بەرهەم','تعديل المنتج','Edit Product','Ürünü Düzenle','ویرایش محصول','Modifier le produit','Produkt bearbeiten',],
      Productupdatedsuccessfully:['بەرهەم بە سەرکەوتوویی نوێکرایەوە','تم تحديث المنتج بنجاح','Product updated successfully','Ürün başarıyla güncellendi','محصول با موفقیت به روز شده','Mise à jour réussie du produit','Produkt erfolgreich aktualisiert',],
      ImageuploadedsuccessfullyclickUpdatetoapplyit:[
        'وێنە بەسەرکەوتوویی بارکرا کرتە بکە لەسەر نوێکردنەوە بۆ جێبەجێ کردنی',
        'تم تحميل الصورة بنجاح انقر على تحديث لتطبيقه','Image uploaded successfully. click Update to apply it','Resim başarıyla yüklendi',
        'تصویر با موفقیت آپلود شد کلیک کنید به روز رسانی آن را اعمال کنید'
        ,'Image téléchargée avec succès Cliquez sur Mettre à jour pour l’appliquer','Bild erfolgreich hochgeladen Klicken Sie auf Aktualisieren, um es anzuwenden',],
      ImageremovedsuccessfullyclickUpdatetoapplyit:[
        'وێنە بە سەرکەوتوویی لابرا کرتە بکە لەسەر نوێکردنەوە بۆ جێبەجێ کردنی',
        'تمت إزالة الصورة بنجاح انقر على تحديث لتطبيقه','Image removed successfully. click Update to apply it','Resim başarıyla kaldırıldı uygulamak için Güncelleye tıklayın',
        'تصویر با موفقیت حذف شد کلیک کنید به روز رسانی آن را اعمال کنید'
        ,'Image supprimée avec succès Cliquez sur Mettre à jour pour l’appliquer','Bild erfolgreich entfernt Klicken Sie auf Aktualisieren, um es anzuwenden',],
      Noimage:['وێنە دیاری نەکراوە','لا توجد صورة','No image','Görüntü yok','هیچ تصویری انتخاب نشده است','Aucune image sélectionnée','Kein Bild ausgewählt',],
      Areyousuretodelete:['ئایا دڵنیایت لە سڕینەوە؟','هل أنت متأكد من الحذف؟','Are you sure to delete','Sileceğinizden emin misiniz?','آیا مطمئن هستید که حذف می کنید؟','Êtes-vous sûr de supprimer?','Sind Sie sicher, dass Sie löschen?',],
      Edit:['دەستکاری','حرر','Edit','Düzenlemek','ویرایش','Éditer','Redigieren',],
      Delete:['سڕینەوە','حذف','Delete','Silmek','حذف','Supprimer','Löschen',],
      Areyousuretocreate:['ئایا دڵنیایت لە دروستکردن؟','هل أنت متأكد من الإنشاء؟','Are you sure to create?','Yaratacağınızdan emin misiniz?','آیا مطمئن هستید که ایجاد می کنید؟','Êtes-vous sûr de créer?','Sind Sie sicher, etwas zu erstellen?',],
      productcreatedsuccessfully:['بەرهەمەکە بە سەرکەوتوویی دروست کراوە','تم إنشاء المنتج بنجاح','product created successfully','ürün başarıyla oluşturuldu','محصول ایجاد شده با موفقیت','Produit créé avec succès','Produkt erfolgreich erstellt',],
      productdeletedsuccessfully:['بەرهەمەکە بە سەرکەوتوویی سڕایەوە','تم حذف المنتج بنجاح','product deleted successfully','ürün başarıyla silindi','محصول حذف شده با موفقیت','Produit supprimé avec succès','Produkt erfolgreich gelöscht',],
      
    },
    dashboard:{
      Sales:['فرۆشتن','مبيعات','Sales','Satış','فروش','Ventes','Umsatz',],
      Dashboard:['کورتە','لوحه القياده','Dashboard','Tablo','داشبورد','Tableau de bord','Instrumententafel'],
      Products:['بەرهەمەکان','منتجات','Products','Ürünler','محصولات','Produits','Produkte'],
      Orders:['داواکاری','طلبات','Orders','Sipariş','سفارشات','Ordres','Aufträge'],
      Users:['بەکارهێنەر','المستخدمين','Users','Kullanıcı','کاربران','Utilisateurs','Benutzer'],
      Categories:['جۆری کاڵا','الفئات','Categories','Kategori','دسته','Catégories','Kategorien'],
      NoSale:['هیچ فرۆشتنێک نیە','لا يوجد بيع','No Sale','Satış Yok','بدون فروش','Pas de vente','Kein Verkauf',],
      LoadingChart:['بارکردنی نەخشە..','تحميل الرسم البياني','Loading Chart...','Yükleme Şeması','نمودار بارگذاری','Chargement du graphique','Diagramm laden',],
      NoCategory:['بێ هاوپۆل','لا توجد فئة','No Category','Kategori Yok','بدون دسته','Aucune catégorie','Keine Kategorie',],
    },
    backEnd: {},
    error: {},
  },
};
export default translator;
